manifest:
  remotes:
    - name: ergohaven
      url-base: https://github.com/ergohaven
  projects:
    - name: ergohaven-zmk
      remote: ergohaven
      # Use the manufacturer's compatible ZMK and driver versions.
      revision: ebba0c8d7f2112a40413b84ff9774195ade05130
      import: config/west.yml
  self:
    path: config
